services:
    web:
        build:
            context: .
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
        volumes:
            - .:/usr/src/web  # при --reload монтирует текущую директорию в рабочую директорию контейнера
    db:
        image: postgres:16.2-alpine3.18
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            -   ./.env.dev
volumes:
    postgres_data:
