services:
#    web:
#        build:
#            context: .
#        command: uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload
#        ports:
#            - "8000:8000"
#        depends_on:
#            - db
#        volumes:
#            - .:/usr/src/web  # при --reload монтирует текущую директорию в рабочую директорию контейнера
    db:
        image: postgres:16.2-alpine3.18
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: exchange
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
